#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall -std=c++1z -fexceptions
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -std=c++1z -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)-lsfml-graphics -lsfml-window -lsfml-system
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = build/Debug_SFML_SimCity_C.exe

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)-lsfml-graphics -lsfml-window -lsfml-system
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = build/Release_SFML_SimCity_C.exe

OBJ_DEBUG = $(OBJDIR_DEBUG)/main.o $(OBJDIR_DEBUG)/World.o $(OBJDIR_DEBUG)/Tile.o $(OBJDIR_DEBUG)/StateMachine.o $(OBJDIR_DEBUG)/MediaHandler.o $(OBJDIR_DEBUG)/Animation.o $(OBJDIR_DEBUG)/MainMenuState.o $(OBJDIR_DEBUG)/MainGameState.o $(OBJDIR_DEBUG)/Gui.o $(OBJDIR_DEBUG)/GameLoop.o $(OBJDIR_DEBUG)/Button.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/main.o $(OBJDIR_RELEASE)/World.o $(OBJDIR_RELEASE)/Tile.o $(OBJDIR_RELEASE)/StateMachine.o $(OBJDIR_RELEASE)/MediaHandler.o $(OBJDIR_RELEASE)/Animation.o $(OBJDIR_RELEASE)/MainMenuState.o $(OBJDIR_RELEASE)/MainGameState.o $(OBJDIR_RELEASE)/Gui.o $(OBJDIR_RELEASE)/GameLoop.o $(OBJDIR_RELEASE)/Button.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d build || mkdir -p build
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/main.o: main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.cpp -o $(OBJDIR_DEBUG)/main.o

$(OBJDIR_DEBUG)/World.o: World.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c World.cpp -o $(OBJDIR_DEBUG)/World.o

$(OBJDIR_DEBUG)/Tile.o: Tile.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Tile.cpp -o $(OBJDIR_DEBUG)/Tile.o

$(OBJDIR_DEBUG)/StateMachine.o: StateMachine.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c StateMachine.cpp -o $(OBJDIR_DEBUG)/StateMachine.o

$(OBJDIR_DEBUG)/MediaHandler.o: MediaHandler.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c MediaHandler.cpp -o $(OBJDIR_DEBUG)/MediaHandler.o

$(OBJDIR_DEBUG)/Animation.o: Animation.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Animation.cpp -o $(OBJDIR_DEBUG)/Animation.o

$(OBJDIR_DEBUG)/MainMenuState.o: MainMenuState.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c MainMenuState.cpp -o $(OBJDIR_DEBUG)/MainMenuState.o

$(OBJDIR_DEBUG)/MainGameState.o: MainGameState.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c MainGameState.cpp -o $(OBJDIR_DEBUG)/MainGameState.o

$(OBJDIR_DEBUG)/Gui.o: Gui.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Gui.cpp -o $(OBJDIR_DEBUG)/Gui.o

$(OBJDIR_DEBUG)/GameLoop.o: GameLoop.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c GameLoop.cpp -o $(OBJDIR_DEBUG)/GameLoop.o

$(OBJDIR_DEBUG)/Button.o: Button.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Button.cpp -o $(OBJDIR_DEBUG)/Button.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf $(OBJDIR_DEBUG)

before_release: 
	test -d build || mkdir -p build
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)/main.o

$(OBJDIR_RELEASE)/World.o: World.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c World.cpp -o $(OBJDIR_RELEASE)/World.o

$(OBJDIR_RELEASE)/Tile.o: Tile.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Tile.cpp -o $(OBJDIR_RELEASE)/Tile.o

$(OBJDIR_RELEASE)/StateMachine.o: StateMachine.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c StateMachine.cpp -o $(OBJDIR_RELEASE)/StateMachine.o

$(OBJDIR_RELEASE)/MediaHandler.o: MediaHandler.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c MediaHandler.cpp -o $(OBJDIR_RELEASE)/MediaHandler.o

$(OBJDIR_RELEASE)/Animation.o: Animation.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Animation.cpp -o $(OBJDIR_RELEASE)/Animation.o

$(OBJDIR_RELEASE)/MainMenuState.o: MainMenuState.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c MainMenuState.cpp -o $(OBJDIR_RELEASE)/MainMenuState.o

$(OBJDIR_RELEASE)/MainGameState.o: MainGameState.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c MainGameState.cpp -o $(OBJDIR_RELEASE)/MainGameState.o

$(OBJDIR_RELEASE)/Gui.o: Gui.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Gui.cpp -o $(OBJDIR_RELEASE)/Gui.o

$(OBJDIR_RELEASE)/GameLoop.o: GameLoop.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c GameLoop.cpp -o $(OBJDIR_RELEASE)/GameLoop.o

$(OBJDIR_RELEASE)/Button.o: Button.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Button.cpp -o $(OBJDIR_RELEASE)/Button.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

